# -*- coding: utf-8 -*-
"""Boostmonoculardepth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/compphoto/BoostingMonocularDepth/blob/main/Boostmonoculardepth.ipynb

#Boosting Monocular Depth Estimation Models to High-Resolution via Content-Adaptive Multi-Resolution Merging

This Colab Notebook contains an inference on the implementation from https://github.com/compphoto/BoostingMonocularDepth.

It supports using [MiDas-v2][1] and [LeRes][2] but not [SGRnet][3].


### Instructions
0. Ensure using a GPU by setting "Runtime/change runtime type" to GPU
1. Run code section 1
2. Put your test images inside /content/inputs
3. Run code section 2 :  it will download the needed model weights for both [MiDas-v2][1] and [LeRes][2]. 

5. Run code section 3
4. Run code section "Ours with MiDas" or "Ours with LeRes" to generate the results 
3. Results will be generated in /content/outputs_midas or /content/outputs_leres folders. 


[1]: https://github.com/intel-isl/MiDaS/tree/v2
[2]: https://github.com/aim-uofa/AdelaiDepth/tree/main/LeReS
[3]: https://github.com/KexianHust/Structure-Guided-Ranking-Loss
"""

# Code section 1

!mkdir -p inputs
!mkdir -p outputs_midas
!mkdir -p outputs_leres

# Code section 2


# Clone git repo
!git clone https://github.com/compphoto/BoostingMonocularDepth.git

!wget https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth
#!gdown https://drive.google.com/u/0/uc?id=1cU2y-kMbt0Sf00Ns4CN2oO9qPJ8BensP&export=download

# Downloading merge model weights
!mkdir -p /content/BoostingMonocularDepth/pix2pix/checkpoints/mergemodel/
!mv latest_net_G.pth /content/BoostingMonocularDepth/pix2pix/checkpoints/mergemodel/

# Downloading Midas weights
!wget https://github.com/AlexeyAB/MiDaS/releases/download/midas_dpt/midas_v21-f6b98070.pt
!mv midas_v21-f6b98070.pt /content/BoostingMonocularDepth/midas/model.pt

# # Downloading LeRes weights
!wget https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download
!mv download /content/BoostingMonocularDepth/res101.pth

# Commented out IPython magic to ensure Python compatibility.
# Code section 3
# %cd BoostingMonocularDepth/

"""> After execution of Code section 3 you can run the following code sections multiple times to generate results but **do not run the previous code sections**. If you did so by mistake use "Runtime/ Reset factory runtime" and then start from step 0."""

# Running the method using MiDas
!python run.py --Final --data_dir /content/inputs --output_dir  /content/outputs_midas/ --depthNet 0

# Running the method using LeRes
!python run.py --Final --data_dir /content/inputs --output_dir  /content/outputs_leres/ --depthNet 2